version: '3.8'

services:
  app:
    build: .
    container_name: sph-app
    restart: unless-stopped
    ports:
      - "8000:3000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./public/img:/app/public/img
    environment:
      - NODE_ENV=production
    networks:
      - proxy-net
      - sph-internal

networks:
  proxy-net:
    external: true
  sph-internal:
    name: sph-internal
